language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
services:
  - mysql
  - postgresql
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite
install:
  - if [ $(phpenv version-name) = "5.5" ]; then composer install --ignore-platform-reqs; else composer install; fi
  - mv config/config.travis.php config/config.php
before_script:
  - mysql -e 'create database traq_test;'
  - psql -c 'create database traq_test' -U postgres
script: vendor/bin/phpunit -c tests/phpunit.xml
matrix:
  allow_failures:
    - php: 5.5
    - env: DB=sqlite
  exclude:
    - php: 5.5
      env: DB=sqlite
    - php: 5.5
      env: DB=postgresql
    - php: 7.0
      env: DB=sqlite
    - php: 7.1
      env: DB=sqlite
    - php: 7.2
      env: DB=sqlite
